name: fe_lab_clinicas_core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  asyncstate: ^2.1.1-dev.1
  signals_flutter: ^5.0.0
  top_snackbar_flutter: ^3.1.0
  loading_animation_widget: ^1.3.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_ddi: ^0.4.0
    #path: ../../flutter_ddi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
